---
name: floorball.news
description: All about the fastest game
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: contact@floorball.news
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sal:
    name: Malek
    site: ''
    avatar: "/assets/images/avatar1.jpg"
    bio: Hi I'm Malek, the author and founder of floorball.news. In my opinion our
      beatiful sport has to grow and I want to help.
    email: contact@floorball.news
    twitter: https://twitter.com/floorballtm
  jane:
    name: Newsroom
    site: ''
    avatar: "/assets/images/avatar2.jpg"
    bio: ''
    email: contact@floorball.news
    twitter: https://twitter.com/
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
